/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.maqueteo_sistema_gestion_contratos.Vista;

/**
 *
 * @author gfa
 */
public class FormularioContratoCivil extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public FormularioContratoCivil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreArrendataria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRucArrendataria = new javax.swing.JTextField();
        txtRepresentanteArrendataria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCargoArrendataria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNacionalidadArrendataria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNacionalidadArrendador = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAntecedentes = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtValorMensual = new javax.swing.JTextField();
        txtFormaPago = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRepresentanteArrendador = new javax.swing.JTextField();
        txtRucArrendador = new javax.swing.JTextField();
        txtCargoArrendador = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtCorreoArrendataria = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtCorreoArrendador = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        txtNombreArrendador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalir.setBackground(new java.awt.Color(204, 255, 255));
        BtnSalir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        BtnSalir.setText("Regresar");
        BtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, -1, -1));

        BtnLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        BtnLimpiar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 650, -1, -1));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setText("Contrato Civil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Comparacientes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Arrendataria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, -1, -1));

        jLabel5.setText("RUC:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txtNombreArrendataria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreArrendataria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArrendatariaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, -1));

        jLabel6.setText("Representante legal:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtRucArrendataria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtRucArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 220, -1));

        txtRepresentanteArrendataria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRepresentanteArrendataria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepresentanteArrendatariaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRepresentanteArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, -1));

        jLabel7.setText("Cargo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        txtCargoArrendataria.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtCargoArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 220, -1));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Arrendador/a:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, -1, -1));

        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 237, -1, -1));

        jLabel10.setText("Representante legal:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 271, -1, -1));

        jLabel13.setText("Nacionalidad:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtNacionalidadArrendataria.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNacionalidadArrendataria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadArrendatariaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNacionalidadArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, -1));

        jLabel14.setText("Nacionalidad:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(txtNacionalidadArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 230, -1));

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel15.setText("Antecedentes:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        txtAntecedentes.setColumns(20);
        txtAntecedentes.setRows(5);
        jScrollPane1.setViewportView(txtAntecedentes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 670, 60));

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel16.setText("Plazo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 240, -1));

        jLabel17.setText("Fecha de inicio de contrato:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel18.setText("Fecha fin de contrato:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 240, -1));

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel19.setText("Canon de arrendamiento:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel20.setText("Valor mensual (dolares):");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel21.setText("Forma de pago:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        txtValorMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorMensualActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 260, -1));
        jPanel1.add(txtFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 110, -1));

        jLabel22.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel22.setText("Deposito de garantía:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel23.setText("Monto de garantía (dolares):");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jLabel24.setText("Nombre:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 237, -1, -1));

        jLabel25.setText("Representante legal:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 271, -1, -1));
        jPanel1.add(txtRepresentanteArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 230, -1));
        jPanel1.add(txtRucArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 220, -1));
        jPanel1.add(txtCargoArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 220, -1));

        jLabel26.setText("RUC:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel27.setText("Cargo:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 266, -1, 30));
        jPanel1.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 260, -1));

        jLabel28.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel28.setText("Correos electrónicos");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel29.setText("Arrendataria: ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));
        jPanel1.add(txtCorreoArrendataria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 250, -1));

        jLabel30.setText("Arrendador/a:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));
        jPanel1.add(txtCorreoArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 230, -1));

        BtnGuardar.setBackground(new java.awt.Color(255, 204, 204));
        BtnGuardar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setActionCommand("Verificar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, -1, 20));
        jPanel1.add(txtNombreArrendador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("* Campo obligatorio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 102));
        jLabel31.setText("*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 10, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 102, 102));
        jLabel32.setText("*");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 10, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 102, 102));
        jLabel33.setText("*");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 102, 102));
        jLabel34.setText("*");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 10, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 102, 102));
        jLabel35.setText("*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 10, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 102, 102));
        jLabel36.setText("*");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 10, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 102, 102));
        jLabel37.setText("*");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 10, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 102, 102));
        jLabel38.setText("*");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 10, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 102, 102));
        jLabel39.setText("*");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 10, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 102, 102));
        jLabel40.setText("*");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 10, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 102, 102));
        jLabel41.setText("*");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 10, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 102, 102));
        jLabel42.setText("*");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 10, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 102, 102));
        jLabel43.setText("*");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 10, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 102, 102));
        jLabel44.setText("*");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 10, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 102, 102));
        jLabel45.setText("*");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 10, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 102, 102));
        jLabel46.setText("*");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 10, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 102, 102));
        jLabel47.setText("*");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 10, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 102, 102));
        jLabel48.setText("*");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 10, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 102, 102));
        jLabel49.setText("*");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void txtNombreArrendatariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArrendatariaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreArrendatariaActionPerformed

    private void txtNacionalidadArrendatariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadArrendatariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadArrendatariaActionPerformed

    private void txtRepresentanteArrendatariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepresentanteArrendatariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepresentanteArrendatariaActionPerformed

    private void txtValorMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorMensualActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombreArrendataria.setText("");
        txtRucArrendataria.setText("");
        txtRepresentanteArrendataria.setText("");
        txtCargoArrendataria.setText("");
        txtNacionalidadArrendataria.setText("");
        txtNombreArrendador.setText("");
        txtRucArrendador.setText("");
        txtRepresentanteArrendador.setText("");
        txtCargoArrendador.setText("");
        txtNacionalidadArrendador.setText("");
        txtAntecedentes.setText("");
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
        txtValorMensual.setText("");
        txtFormaPago.setText("");
        txtGarantia.setText("");
        txtCorreoArrendataria.setText("");
        txtCorreoArrendador.setText("");
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioContratoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioContratoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioContratoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioContratoCivil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioContratoCivil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnGuardar;
    public javax.swing.JButton BtnLimpiar;
    public javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtAntecedentes;
    public javax.swing.JTextField txtCargoArrendador;
    public javax.swing.JTextField txtCargoArrendataria;
    public javax.swing.JTextField txtCorreoArrendador;
    public javax.swing.JTextField txtCorreoArrendataria;
    public javax.swing.JTextField txtFechaFin;
    public javax.swing.JTextField txtFechaInicio;
    public javax.swing.JTextField txtFormaPago;
    public javax.swing.JTextField txtGarantia;
    public javax.swing.JTextField txtNacionalidadArrendador;
    public javax.swing.JTextField txtNacionalidadArrendataria;
    public javax.swing.JTextField txtNombreArrendador;
    public javax.swing.JTextField txtNombreArrendataria;
    public javax.swing.JTextField txtRepresentanteArrendador;
    public javax.swing.JTextField txtRepresentanteArrendataria;
    public javax.swing.JTextField txtRucArrendador;
    public javax.swing.JTextField txtRucArrendataria;
    public javax.swing.JTextField txtValorMensual;
    // End of variables declaration//GEN-END:variables
}
